version: '3.5'

services:
    corona-db:
        image: postgres:latest
        container_name: corona-db
        restart: always
        ports:
            - 4000:4000
        environment:
            POSTGRES_PASSWORD: root
        volumes: 
            - corona-db-data:/var/lib/postgres/data


networks:
    default:
        name: "thdp-dev"

volumes:
    corona-db-data:
        driver: local